### ISSUE TITLE
February Roadmap

### ISSUE THREAD

**Issue by jaensen** [circlesland/o-platform#654]
- [x] #655
- [ ] #656
- [ ] #657
- [ ] - spezifikation und suche/beauftragung dev-ops
- [ ] #664
- [ ] #665
- [ ] #666
- [ ] #667
- [ ] - event (wie kommen die invite codes auf die Dose?)
- [ ] - event actions (chat etc.)
